apiVersion: v1
kind: Service
metadata:
  name: fast-api-docker-service
  namespace: test-namespace
  labels:
    app: fast-api-docker
spec:
  type: NodePort
  selector:
    app: fast-api-docker
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP